### ISSUE TITLE
Snippet filename meanings

### ISSUE THREAD

**Issue by Alfusainey** [fischerfel/TUM-Crypto#2]
@fischerfel: What does the second number in the snippet filename means?

 Example: `Snippet10058995_34413.java` has two numbers and it looks like `10058995` is the post ID. What does the `34413` stands for?

**Comment by fischerfel** [comment]
It's `Snippet<postid>_<snippetid>.java`. The latter is the unique ID of a snippet. We generated it, it's not part of the SO database schema.

**Comment by Alfusainey** [comment]
I see, thanks 👍 

one last question before I close this issue: which `release` of the SO data dump did you use?

**Comment by Alfusainey** [comment]
@fischerfel should I open a new issue for the release of the SO dump you used in your paper?

**Comment by fischerfel** [comment]
March 2018
